# We're using version 3.7 of the Docker Compose file format
version: "3.7"

# Define services/containers
services: 
  web: 
    image:  php:7.1-apache
    restart: always
    volumes: 
      - ./volumes/html:/var/www/html
    ports:
      - "80:80"
    networks:
      - my-network 
  # MySQL container
  mysql: 
    # Use mysql:5.7 image
    image: mysql:5.7
    # Connect to "my-network" network, as defined below
    restart: always
    networks:
      - my-network
    # Pass a list of environment variables to the container
    environment:
      MYSQL_ROOT_PASSWORD: root

  # phpMyAdmin container
  phpmyadmin: 
    # Use phpmyadmin/phpmyadmin:5.0.2 image
    image: phpmyadmin/phpmyadmin:5.0.2
    restart: always
    # Connect to "my-network" network, as defined below
    networks:
      - my-network
    # Map port 8080 on the host to port 80 inside the container
    # Syntax is: "HOST_PORT:CONTAINER_PORT"
    ports:
      - "8080:80"
    # Pass a list of environment variables to the container
    environment:
      PMA_HOST: mysql
    # Wait for "mysql" container to start first
    depends_on:
      - mysql

# Define networks
networks:
  my-network:
