# We're using version 3.7 of the Docker Compose file format
version: "3.7"

# Define services/containers
services:
  # MySQL container
  mysql:
    # Use mysql:8.0.19 image
    image: mysql:8.0.19
    # Volume
    volumes:
      - ./mydb:/var/lib/mysql   
      #- ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    command:
      --max_allowed_packet=1000M
      --sql-mode=NO_AUTO_VALUE_ON_ZERO
      #--local-infile = 1來修改許可權是的可以載入本地檔案。local-infile = 0 則禁止
      #--secure_file_priv = ''：不做任何限制，可以隨意的 Import 或 Export。
    # Connect to "my-network" network, as defined below
    networks:
      - my-network
    # Pass a list of environment variables to the container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw

  # phpMyAdmin container
  phpmyadmin:
    # Use phpmyadmin/phpmyadmin:5.0.2 image
    image: phpmyadmin/phpmyadmin:5.0.2
    # Connect to "my-network" network, as defined below
    networks:
      - my-network
    # Map port 8080 on the host to port 80 inside the container
    # Syntax is: "HOST_PORT:CONTAINER_PORT"
    ports:
      - "8080:80"
    # Pass a list of environment variables to the container
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 1600M  
    # Wait for "mysql" container to start first
    depends_on:
      - mysql

# Define networks
networks:
  my-network:
